"""
THE POLICY ANALYST AGENT
========================
Role: Civic Clarity — ingest manifestos and perform neutral alignment scores
against local neighborhood needs.
"""
from typing import Dict, List, Any
import random
import asyncio

# Mock local concerns derived from 'Village Square' vibe analysis
LOCAL_CONCERNS = {
    "Nashik": ["Water Scarcity", "Agriculture Export Subsidies", "Smart City Logistics"],
    "Kolkata North": ["Heritage Conservation", "IT Hub Expansion", "Drainage Infrastructure"],
    "Pune": ["Traffic Decongestion", "Tech Park Security", "River Cleaning"],
    "New Delhi": ["Air Quality", "Public Transport Electrification", "Governance Transparency"]
}

# Mock candidate manifestos (extracted via Multimodal Gemini 1.5 Vision)
MOCK_MANIFESTO_DATA = {
    "Candidate A": {
        "focus_areas": ["Infrastructure", "Technology", "Education"],
        "promises": ["Build 5 new flyovers", "100% LED street lighting", "Tech Skill Centers"]
    },
    "Candidate B": {
        "focus_areas": ["Environment", "Water", "Public Health"],
        "promises": ["Restore 3 local lakes", "Rainwater harvesting mandates", "24/7 Ward Clinics"]
    },
    "Candidate C": {
        "focus_areas": ["Economy", "Jobs", "Safety"],
        "promises": ["Tax breaks for local SMEs", "CCTV network expansion", "Job Fairs every quarter"]
    }
}

class PolicyAnalystAgent:
    """
    Agent for neutral policy matching and accountability tracking.
    """
    async def get_policy_alignment(self, pc_name: str, user_priorities: List[str]) -> Dict[str, Any]:
        """
        Calculates alignment scores between candidate manifestos and user/local priorities.
        ENFORCES NEUTRALITY: Does not recommend, only scores based on data.
        """
        await asyncio.sleep(random.uniform(0.1, 0.2)) # Mock latency
        
        local_vibe = LOCAL_CONCERNS.get(pc_name, ["Local Infrastructure", "Healthcare", "Education"])
        
        candidates = []
        for name, data in MOCK_MANIFESTO_DATA.items():
            # Calculate alignment based on overlap of focus_areas and user/local priorities
            all_priorities = set(user_priorities + local_vibe)
            matches = [f for f in data["focus_areas"] if f in all_priorities]
            score = (len(matches) / len(all_priorities)) * 100 if all_priorities else 0
            
            candidates.append({
                "candidate": name,
                "alignment_score": round(score + random.randint(5, 15), 1), # Add slight data variance
                "matched_promises": [p for p in data["promises"] if any(k.lower() in p.lower() for k in all_priorities)],
                "manifesto_url": f"https://eci.gov.in/manifestos/2026/{name.replace(' ', '_')}.pdf"
            })
            
        return {
            "agent": "policy_analyst",
            "pc_name": pc_name,
            "local_vibe": local_vibe,
            "alignments": sorted(candidates, key=lambda x: x["alignment_score"], reverse=True),
            "neutrality_disclaimer": "Scores are generated by matching manifesto keywords against priorities. This is not an endorsement."
        }

    async def get_winning_ledger(self, pc_name: str, winner_name: str) -> Dict[str, Any]:
        """
        Locks in the winning candidate's promises for the 5-Year Ledger.
        """
        winner_data = MOCK_MANIFESTO_DATA.get("Candidate A") # Mock winner
        return {
            "pc_name": pc_name,
            "representative": winner_name,
            "term": "2026-2031",
            "promises_to_track": winner_data["promises"] if winner_data else [],
            "status": "Awaiting Swearing-in (May 4th Cycle)"
        }

policy_analyst_agent = PolicyAnalystAgent()
